# Generated by Django 5.1.2 on 2024-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_students_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post/photos/'),
        ),
    ]
