# Generated by Django 5.1.2 on 2024-12-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_alter_students_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Brands',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Cars',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='course',
            new_name='brand',
        ),
    ]
