# Generated by Django 5.1.2 on 2024-12-15 13:35

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_rename_course_brands_rename_students_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_name',
            field=models.CharField(default=builtins.print, max_length=150),
            preserve_default=False,
        ),
    ]
