# Generated by Django 5.1.2 on 2024-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_cars_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(default='bmw', max_length=150),
        ),
    ]
