# Generated by Django 5.1.2 on 2024-12-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_remove_cars_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='email',
            new_name='car_name',
        ),
    ]
