# Generated by Django 5.1.2 on 2024-12-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_rename_email_cars_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_name',
        ),
        migrations.AddField(
            model_name='cars',
            name='email',
            field=models.CharField(default='bmw@gmail.com', max_length=150),
        ),
    ]
